name: Setup repo
description: "Checkout, and install mille-feuille with dev requirements"

inputs:
  python-version:
    description: "Version range or exact version of Python or PyPy to use"
    required: true
    type: string

  oneapi:
    description: "Intel OneAPI version to use"
    required: true
    type: string

  cached:
    description: "Does cached install of IntelOneAPI exist?"
    required: true

env:
  CTEST_NO_TESTS_ACTION: error

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies (cpu)
      run: |
        pip install --upgrade pip
        pip install .[dev]
      shell: bash

    - name: non-cache install oneAPI
      # timeout-minutes: 5
      run: |
        if [ "${{ inputs.cached }}" = "true" ]; then
          echo "Cache hit! No install required"
        else
          sh -c .github/actions/setup_repo/oneapi_setup_apt_repo_linux.sh
          sudo apt install --no-install-recommends \
            intel-oneapi-compiler-fortran-${{ inputs.oneapi }} \
            intel-oneapi-compiler-dpcpp-cpp-${{ inputs.oneapi }} \
            intel-oneapi-mpi \
            intel-oneapi-mpi-devel \
            intel-oneapi-mkl-${{ inputs.oneapi }} \
            intel-oneapi-mkl-devel-${{ inputs.oneapi }}
        fi
      shell: bash

    - name: Setup Intel oneAPI environment
      run: |
        source /opt/intel/oneapi/setvars.sh
        printenv >> $GITHUB_ENV
      shell: bash

    - name: Compile test executables
      working-directory: ./tests/test_exe
      run: |
        mpiifx -g -traceback -r8 fmain.f90 -o fmain
        mpiicpx -g -traceback cxxmain.cpp -o cxxmain
      shell: bash

    - name: exclude unused files from cache
      run: |
        if [ "${{ inputs.cached }}" = "true" ]; then
          echo "Cache hit! No clean up required"
        else
          sh -c .github/actions/setup_repo/oneapi_cache_exclude_linux.sh
        fi
      shell: bash
